--------------------------------------------------------
--  File created - Saturday-December-07-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INTERESTS
--------------------------------------------------------

  CREATE TABLE "CIS550PROJECT"."INTERESTS" 
   (	"USERID" NUMBER(*,0), 
	"INTEREST" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CIS550PROJECT.INTERESTS
SET DEFINE OFF;
Insert into CIS550PROJECT.INTERESTS (USERID,INTEREST) values (1,'Baseball');
Insert into CIS550PROJECT.INTERESTS (USERID,INTEREST) values (1,'Basketball');
Insert into CIS550PROJECT.INTERESTS (USERID,INTEREST) values (1,'Hockey');
Insert into CIS550PROJECT.INTERESTS (USERID,INTEREST) values (2,'Baseball');
Insert into CIS550PROJECT.INTERESTS (USERID,INTEREST) values (25,'Computers');
Insert into CIS550PROJECT.INTERESTS (USERID,INTEREST) values (29,'Phones');
--------------------------------------------------------
--  DDL for Index INTERESTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CIS550PROJECT"."INTERESTS_PK" ON "CIS550PROJECT"."INTERESTS" ("USERID", "INTEREST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INTERESTS
--------------------------------------------------------

  ALTER TABLE "CIS550PROJECT"."INTERESTS" ADD CONSTRAINT "INTERESTS_PK" PRIMARY KEY ("USERID", "INTEREST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CIS550PROJECT"."INTERESTS" MODIFY ("INTEREST" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."INTERESTS" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table INTERESTS
--------------------------------------------------------

  ALTER TABLE "CIS550PROJECT"."INTERESTS" ADD CONSTRAINT "INTERESTS_USERS_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "CIS550PROJECT"."USERS" ("USERID") ENABLE;
