--------------------------------------------------------
--  File created - Saturday-December-07-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PINS
--------------------------------------------------------

  CREATE TABLE "CIS550PROJECT"."PINS" 
   (	"OBJECTID" NUMBER(*,0), 
	"SOURCEID" VARCHAR2(255 CHAR), 
	"USERID" NUMBER(*,0), 
	"BOARDID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CIS550PROJECT.PINS
SET DEFINE OFF;
Insert into CIS550PROJECT.PINS (OBJECTID,SOURCEID,USERID,BOARDID) values (1,'TBD',1,27);
Insert into CIS550PROJECT.PINS (OBJECTID,SOURCEID,USERID,BOARDID) values (2,'TBD',2,22);
Insert into CIS550PROJECT.PINS (OBJECTID,SOURCEID,USERID,BOARDID) values (3,'TBD',3,35);
Insert into CIS550PROJECT.PINS (OBJECTID,SOURCEID,USERID,BOARDID) values (4,'TBD',4,36);
Insert into CIS550PROJECT.PINS (OBJECTID,SOURCEID,USERID,BOARDID) values (4,'TBD',23,42);
--------------------------------------------------------
--  DDL for Index PINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CIS550PROJECT"."PINS_PK" ON "CIS550PROJECT"."PINS" ("OBJECTID", "SOURCEID", "USERID", "BOARDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PINS
--------------------------------------------------------

  ALTER TABLE "CIS550PROJECT"."PINS" ADD CONSTRAINT "PINS_PK" PRIMARY KEY ("OBJECTID", "SOURCEID", "USERID", "BOARDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CIS550PROJECT"."PINS" MODIFY ("BOARDID" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."PINS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."PINS" MODIFY ("SOURCEID" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."PINS" MODIFY ("OBJECTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PINS
--------------------------------------------------------

  ALTER TABLE "CIS550PROJECT"."PINS" ADD CONSTRAINT "PINS_OBJECTS_FK1" FOREIGN KEY ("OBJECTID", "SOURCEID")
	  REFERENCES "CIS550PROJECT"."OBJECTS" ("OBJECTID", "SOURCEID") ENABLE;
  ALTER TABLE "CIS550PROJECT"."PINS" ADD CONSTRAINT "PINS_USERS_FK1" FOREIGN KEY ("BOARDID", "USERID")
	  REFERENCES "CIS550PROJECT"."BOARDS" ("BOARDID", "USERID") ENABLE;
