--------------------------------------------------------
--  File created - Saturday-December-07-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "CIS550PROJECT"."USERS" 
   (	"USERID" NUMBER(*,0), 
	"FIRSTNAME" VARCHAR2(255 CHAR), 
	"LASTNAME" VARCHAR2(255 CHAR), 
	"EMAILID" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(511 CHAR), 
	"AFFILIATION" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CIS550PROJECT.USERS
SET DEFINE OFF;
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (1,'Tom','Cruise','tom.cruise@gmail.com','123456','Hollywood Actor');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (2,'Amitabh ','Bacchan','amitabh.bacchan@gmail.com','123456','Bollywood Actor');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (3,'Arvind','Kejriwal','arvind.kejriwal@gmail.com','123456','Indian Politician');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (4,'Stephen','Fry','stephen.fry@gmail.com','123456','British Presenter');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (22,'Shahrukh','Khan','shahrukh.khan@gmail.com','123456','Bollywood Actor');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (23,'Jennifer','Lawrence','jennifer.lawrence@gmail.com','123456','Hollywood Actor');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (24,'Zach','Ives','zach.ives@gmail.com','123456','UPenn Professor');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (25,'Charlie ','Chaplin','charlie.chaplin@gmail.com','123456','Comedian');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (26,'George','Bush','george.bush@gmail.com','123456','US Politician');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (27,'Jason','Statham','jason.statham@gmail.com','123456','Hollywood Actor');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (28,'Sachin','Tendular','sachin.tendulkar@gmail.com','123456','Indian Cricketer');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (29,'Bill','Gates','bill.gates@gmail.com','123456','Programming Whiz');
Insert into CIS550PROJECT.USERS (USERID,FIRSTNAME,LASTNAME,EMAILID,PASSWORD,AFFILIATION) values (41,'Manmohan','Singh','manmohan.singh@gmail.com','123456','Indian Politician');
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CIS550PROJECT"."USERS_PK" ON "CIS550PROJECT"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CIS550PROJECT"."USERS_UK1" ON "CIS550PROJECT"."USERS" ("EMAILID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "CIS550PROJECT"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("EMAILID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CIS550PROJECT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CIS550PROJECT"."USERS" MODIFY ("AFFILIATION" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."USERS" MODIFY ("EMAILID" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."USERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."USERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."USERS" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger USERS_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CIS550PROJECT"."USERS_SEQ" before insert on Users for each row begin select users_seq.nextval into :new.userID from dual;
end;
/
ALTER TRIGGER "CIS550PROJECT"."USERS_SEQ" ENABLE;
