--------------------------------------------------------
--  File created - Saturday-December-07-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RATING
--------------------------------------------------------

  CREATE TABLE "CIS550PROJECT"."RATING" 
   (	"OBJECTID" NUMBER(*,0), 
	"USERID" NUMBER(*,0), 
	"SCORE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CIS550PROJECT.RATING
SET DEFINE OFF;
Insert into CIS550PROJECT.RATING (OBJECTID,USERID,SCORE) values (1,1,5);
Insert into CIS550PROJECT.RATING (OBJECTID,USERID,SCORE) values (2,4,5);
Insert into CIS550PROJECT.RATING (OBJECTID,USERID,SCORE) values (3,4,1);
Insert into CIS550PROJECT.RATING (OBJECTID,USERID,SCORE) values (10,27,4);
Insert into CIS550PROJECT.RATING (OBJECTID,USERID,SCORE) values (7,24,2);
Insert into CIS550PROJECT.RATING (OBJECTID,USERID,SCORE) values (6,28,2);
Insert into CIS550PROJECT.RATING (OBJECTID,USERID,SCORE) values (4,29,1);
--------------------------------------------------------
--  DDL for Index RATING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CIS550PROJECT"."RATING_PK" ON "CIS550PROJECT"."RATING" ("OBJECTID", "USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RATING
--------------------------------------------------------

  ALTER TABLE "CIS550PROJECT"."RATING" ADD CONSTRAINT "RATING_CHK1" CHECK (SCORE BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "CIS550PROJECT"."RATING" ADD CONSTRAINT "RATING_PK" PRIMARY KEY ("OBJECTID", "USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CIS550PROJECT"."RATING" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."RATING" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "CIS550PROJECT"."RATING" MODIFY ("OBJECTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RATING
--------------------------------------------------------

  ALTER TABLE "CIS550PROJECT"."RATING" ADD CONSTRAINT "RATING_OBJECTS_FK1" FOREIGN KEY ("OBJECTID")
	  REFERENCES "CIS550PROJECT"."OBJECTS" ("OBJECTID") ENABLE;
  ALTER TABLE "CIS550PROJECT"."RATING" ADD CONSTRAINT "RATING_USERS_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "CIS550PROJECT"."USERS" ("USERID") ENABLE;
